### ISSUE TITLE
加载出现错误 如图

### ISSUE THREAD

**Issue by fuqiang03** [openwrt-develop/ndpi-netfilter#1]
![qq 20180411204804](https://user-images.githubusercontent.com/26851715/38617470-bad8b8e0-3dc9-11e8-957c-2fc1b06f4147.png)
17.04版本

**Comment by panda-mute** [comment]
是和lede源码一起编译的么？

**Comment by fuqiang03** [comment]
对的

**Comment by fuqiang03** [comment]
上一个版本没有出现这种情况

**Comment by panda-mute** [comment]
@fuqiang03 Please check the latest version:
9fb2c26fa57b78571ff71306a91f7afd793f73b6

**Comment by fuqiang03** [comment]
谢谢

**Comment by fuqiang03** [comment]
我还有个小问题  以前用atmaterial控制页面重启路由器正常   现在是点完重启 不会出现登入页面了  直接弹出了主页  但这个时候 路由器还没有完成重启 ，请大神看下
